spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
    username: sa
    password:
  jpa:
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create
        use_sql_comments: true
#  jackson:
#    serialization:
#      fail_on_empty_beans: false

logging:
  level:
    org:
      hibernate:
        #SQL: DEBUG
        type:
          trace